- name: Installer et démarrer Apache
  hosts: all
  become: yes

  tasks:
    - name: Installer le serveur Apache
      apt:
        name: apache2
        state: present

    - name: Démarrer le serveur Apache
      service:
        name: apache2
        state: started
        enabled: yes
